/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: Unknown
*/

#include <defs.h>



//----- (00010000) --------------------------------------------------------
#error "10000: only 32bit functions can be decompiled (funcsize=0)"

#error "There were 1 decompilation failure(s) on 1 function(s)"
